# ---- build stage ----
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# ---- run stage ----
FROM node:18-alpine
WORKDIR /app
RUN npm i -g serve
COPY --from=build /app/dist ./dist

# Pakai port 5173 agar tidak bentrok dengan backend di 3000
EXPOSE 5173
CMD ["serve", "-s", "dist", "-l", "5173"]
